name: remote ssh command
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: executing remote ssh command using ssh key
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/gh-actions/mailer-api
          git fetch origin main
          git pull origin main
          docker build -t mailer-img .
          docker run -dp 80:3000 mailer-img:latest